# Generated by Django 5.2.5 on 2025-08-26 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_category_comment_parent_post_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
